module otter.jvm.workbookapp.main {
    requires java.datatransfer;
    requires java.desktop;
    requires java.sql;
    requires javax.inject;
    requires com.fasterxml.jackson.annotation;
    requires com.fasterxml.jackson.core;
    requires com.fasterxml.jackson.databind;
    requires com.fasterxml.jackson.dataformat.yaml;
    requires com.fasterxml.jackson.kotlin;
    requires com.install4j.runtime;
    requires com.jfoenix;
    requires com.jthemedetector;
    requires dagger;
    requires io.reactivex.rxjava2;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires javautil;
    requires kotlin.resource.container;
    requires kotlin.stdlib;
    requires kotlin.stdlib.common;
//    requires mockk.dsl.jvm;
//    requires mockk.jvm;
    requires org.apache.logging.log4j.core;
    requires org.controlsfx.controls;
    requires org.jooq;
    requires org.json;
    requires org.kordamp.ikonli.fontawesome;
    requires org.kordamp.ikonli.javafx;
    requires org.kordamp.ikonli.material;
    requires org.kordamp.ikonli.materialdesign;
    // requires org.testfx.monocle;
    requires org.xerial.sqlitejdbc;
    requires rxkotlin;
    requires rxkotlinfx;
    requires rxrelay;
    requires sentry;
    requires org.slf4j;
    requires tornadofx;
    requires otter.common.audio;
    requires otter.common;
    requires otter.jvm.controls;
    requires otter.jvm.device;
    requires otter.jvm.utils;
    requires otter.jvm.workbookplugin;
    requires java.compiler;
    requires otter.assets;
    requires org.apache.logging.log4j;
    requires otter.common;
}