plugins {
    id 'org.openjfx.javafxplugin' version "$javafxPluginVer"
}

ext.jpmsModuleName = 'org.wycliffeassociates.otter.jvm.workbookplugin'
apply from: rootProject.file('gradle/jpms-kotlin.gradle')

javafx {
    version = "$javafxVer"
    modules = ['javafx.controls', 'javafx.fxml']
}

repositories {
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' } // TornadoFX 2.0 Snapshot
}

dependencies {
    // TornadoFX
    implementation "no.tornado:tornadofx2:$tornadofxVer"
}
