plugins {
    id 'java-library'
}

group = 'org.wycliffeassociates.otter.common'
version = '0.4.3'

ext.jpmsModuleName = 'org.wycliffeassociates.otter.common.audio'
apply from: rootProject.file('gradle/jpms-kotlin.gradle')

dependencies {
    testImplementation "junit:junit:$junitVer"

    api "org.slf4j:slf4j-api:$slf4jApiVer"
    api "javazoom.jl:SeekableJlayer:$jlayerVer"
    api "org.digitalmediaserver:cuelib-core:$cuelibVer"
    api "org.bibletranslationtools:kotlin-vtt:$kotlinVttVer"
    api "com.mpatric:mp3agic:$mp3TagVer"
    api "be.tarsos:tarsosdsp:$tarsosDspVer"
}
